// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf_atfJ1Qehio88ru1bhXg7POPTLJa9V4',
    appId: '1:438367487483:web:70856235985389d22db75e',
    messagingSenderId: '438367487483',
    projectId: 'mm-player-af72f',
    authDomain: 'mm-player-af72f.firebaseapp.com',
    storageBucket: 'mm-player-af72f.appspot.com',
    measurementId: 'G-M2CEQQC14F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08qyAq5PIJNnXYkFmG_Tt03WFR6uRcvI',
    appId: '1:438367487483:android:30106af7c9e8d95f2db75e',
    messagingSenderId: '438367487483',
    projectId: 'mm-player-af72f',
    storageBucket: 'mm-player-af72f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxGhDIKGKq3T3XPsAxSOmRfn7Lm1IjtY',
    appId: '1:438367487483:ios:91eaac203370a12d2db75e',
    messagingSenderId: '438367487483',
    projectId: 'mm-player-af72f',
    storageBucket: 'mm-player-af72f.appspot.com',
    iosClientId: '438367487483-b3ul025v9ttto0riascvku20bgiqtqej.apps.googleusercontent.com',
    iosBundleId: 'com.example.bongomart.bongoMart',
  );

}